### ISSUE TITLE
Feeds are not updating

### ISSUE THREAD

**Issue by herndlm** [jplitza/nina_xmpp#10]
Hi,

I think there might be a problem with your hosted instance as it seems to be not updating the feeds.

Output of `feeds`
```
https://warnung.bund.de/bbk.biwapp/warnmeldungen.json (zuletzt aktualisiert: Mon, 16 Aug 2021 08:07:52 GMT)
https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json (zuletzt aktualisiert: Mon, 16 Aug 2021 22:33:00 GMT)
https://warnung.bund.de/bbk.lhp/hochwassermeldungen.json (zuletzt aktualisiert: Mon, 16 Aug 2021 22:25:12 GMT)
https://warnung.bund.de/bbk.dwd/unwetter.json (zuletzt aktualisiert: Mon, 16 Aug 2021 22:31:29 GMT)
https://warnung.bund.de/bbk.katwarn/warnmeldungen.json (zuletzt aktualisiert: Mon, 16 Aug 2021 21:21:54 GMT)
```

I guess you're basically not supporting that instance but I wanted to report this, as it seems to be more global, before  trying to host my own.

Btw. I think this project is a great idea and appreciate it very much!

**Comment by herndlm** [comment]
Fyi I started debugging this, might be related or not but there is definitely a problem in case the async job throws an exception, e.g.
- start application, see feeds updating every x seconds
- cause an exception by disabling the network connection
- reconnect the network
- see feeds not updating anymore because the task was killed with a `CancelledError`

I'm not a python dev, but am happy to help out here and learn a thing or the other potentially. Feel free to improve/fix this if you know what's going on, if not or you're busy, I'll try too

**Comment by jplitza** [comment]
Damn, I hoped you had a lead on this. 😅
I noticed this behavior some weeks ago, but still have to set up proper logging to debug it.

**Comment by herndlm** [comment]
Well I started running/using it on my raspberry pi now, so I'll take a close look there too

**Comment by herndlm** [comment]
Oh this is interesting. I can reproduce it at least. It just randomly stops as in
```
DEBUG:NinaXMPP
:Finished updating feeds, sleeping for 10s
INFO:NinaXMPP:
Updating feed https://warnung.bund.de/bbk.biwapp/warnmeldung
en.json (last modified: Sun, 22 Aug 2021 09:37:43 GMT)
INFO:NinaXMPP:
Updating feed https://warnung.bund.de/bbk.mowas/gefahrendurc
hsagen.json (last modified: Sun, 22 Aug 2021 12:03:44 GMT)
INFO:NinaXMPP:
Updating feed https://warnung.bund.de/bbk.lhp/hochwassermeld
ungen.json (last modified: Sun, 22 Aug 2021 13:10:13 GMT)
INFO:NinaXMPP:
Updating feed https://warnung.bund.de/bbk.dwd/unwetter.json
(last modified: Sun, 22 Aug 2021 13:18:48 GMT)
```

I don't know enough about Python, the libs and the app yet but I wonder if it is dead-locking the DB or something similar. Will continue later..

**Comment by herndlm** [comment]
I have found at least the problem that disguises the _actual_ problem.

Apparently if there is a reference to a task and the task is not finished yet (because of the SIGINT loop) it will not be garbage collected and this seems to be not triggering its error handling => if any exception is raised inside the task we will never see inside _unless_ we kill app / task. https://bugs.python.org/issue28274 is related
I can verify this by raising any exception in the task which will never be shown except I manually send SIGINT to the process or CTRL-C it.

So I assume some HTTP or parse error is happening but we just don't see it because of the SIGINT loop.

I suggest to improve this first, by failing early if the task fails, e.g. by either using https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.add_done_callback or refactoring the SIGINT loop somehow. Then the actual update feeds task can be hardened. I can at least try to improve it :)
